# Cripting Lybrary
crypt =	{
      "A": "1630",
      "a": "GOOG",
      "B": "ACTI",
      "b": "AVTI",
      "C": "BOBO",
      "c": "BORS",
      "D": "ARIL",
      "d": "#§%!",
      "E": "##%{",
      "e": "##%}",
      "F": "!!!!",
      "f": "#++*",
      "G": "*/*-",
      "g": "+##!",
      "H": "+--*",
      "h": "[]]]",
      "I": "ßßßß",
      "i": "?ß?ß",
      "J": "MUST",
      "j": ",,,,",
      "K": "1234",
      "k": "-_.;",
      "L": "=785",
      "l": "tang",
      "M": "+*~*",
      "m": "tT52",
      "N": "dfgh",
      "n": "a@wd",
      "O": "äölk",
      "o": "µ}&?",
      "P": "+~+€",
      "p": "€€€€",
      "Q": "$$$$",
      "q": "€$$€",
      "R": "$€€$",
      "r": "/*-+",
      "S": "7855",
      "s": "3214",
      "T": "5$§@",
      "t": "ALGO",
      "U": "a\ß*",
      "u": "algo",
      "V": "5587",
      "v": "ü#;,",
      "W": ":.,;",
      "w": "stan",
      "X": "0([)",
      "x": "=ios",
      "Y": "=[(]",
      "y": "([)=",
      "Z": "aBBa",
      "z": "BaaB",
      " ": "BOOG",
      "*": "(AT)",
      "/": "(TA)",
      "+": "T()A",
      "-": "(TA(",
      "1": "ö00ö",
      "2": "WSOO",
      "3": "54eD",
      "4": "USUs",
      "5": "G!OG",
      "6": "G@OG",
      "7": "(@€)",
      "8": "(@€]",
      "9": "[@])",
      "0": "(45(",
      "(": "<()>",
      ")": ">[]<",
}
# reverse Cripting Lybrary
decrypt = {
    crypt["A"]: "A",
    crypt["a"]: "a",
    crypt["B"]: "B",
    crypt["b"]: "b",
    crypt["C"]: "C",
    crypt["c"]: "c",
    crypt["D"]: "D",
    crypt["d"]: "d",
    crypt["E"]: "E",
    crypt["e"]: "e",
    crypt["F"]: "F",
    crypt["f"]: "f",
    crypt["G"]: "G",
    crypt["g"]: "g",
    crypt["H"]: "H",
    crypt["h"]: "h",
    crypt["I"]: "I",
    crypt["i"]: "i",
    crypt["J"]: "J",
    crypt["j"]: "j",
    crypt["K"]: "k",
    crypt["k"]: "k",
    crypt["L"]: "L",
    crypt["l"]: "l",
    crypt["M"]: "M",
    crypt["m"]: "m",
    crypt["N"]: "N",
    crypt["n"]: "n",
    crypt["O"]: "O",
    crypt["o"]: "o",
    crypt["P"]: "P",
    crypt["p"]: "p",
    crypt["Q"]: "Q",
    crypt["q"]: "q",
    crypt["R"]: "R",
    crypt["r"]: "r",
    crypt["S"]: "S",
    crypt["s"]: "s",
    crypt["T"]: "T",
    crypt["t"]: "t",
    crypt["U"]: "U",
    crypt["u"]: "u",
    crypt["V"]: "V",
    crypt["v"]: "v",
    crypt["W"]: "W",
    crypt["w"]: "w",
    crypt["X"]: "X",
    crypt["x"]: "x",
    crypt["Y"]: "Y",
    crypt["y"]: "y",
    crypt["Z"]: "Z",
    crypt["z"]: "z",
    crypt[" "]: " ",
    crypt["*"]: "*",
    crypt["/"]: "/",
    crypt["+"]: "+",
    crypt["-"]: "-",
    crypt["1"]: "1",
    crypt["2"]: "2",
    crypt["3"]: "3",
    crypt["4"]: "4",
    crypt["5"]: "5",
    crypt["6"]: "6",
    crypt["7"]: "7",
    crypt["8"]: "8",
    crypt["9"]: "9",
    crypt["0"]: "0",
    crypt["("]: "(",
    crypt[")"]: ")",
}

def crypting(text):
  x = 0
  text2 = ""
  while x < len(text):
    text2 = text2 + crypt[text[x]]
    x = x + 1
  return text2


def decrypting(text):
  text1 = [text[i:i+4] for i in range(0, len(text), 4)]
  text2 = ""
  for t in text1:
    text2 = text2 + decrypt[t]
  return text2
